---
- name: Add an apt signing key for Elastic
  ansible.builtin.shell: >-
    curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch |
    gpg --dearmor -o /usr/share/keyrings/elastic.gpg

- name: Add apt repository for Elastic
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/elastic.gpg] https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: Install filebeat
  ansible.builtin.apt:
    name: filebeat
    state: present
    update_cache: yes
  notify: restart filebeat

- name: Copy filebeat configuration to /etc/filebeat/filebeat.yml
  ansible.builtin.template:
    src: ../templates/filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0600
  notify:
    - restart filebeat
