---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: Remove default nginx config
  ansible.builtin.file:
    name: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Generate admin password for Kibana
  ansible.builtin.shell: >-
    echo "{{ kibana_admin_password }}" | openssl passwd -apr1 -stdin
  register: kibana_password

- name: Create Kibana auth credentials for nginx
  ansible.builtin.template:
    src: ../templates/htpasswd.users.j2
    dest: /etc/nginx/htpasswd.users
    mode: 0644
  notify: restart nginx

- name: Create elk config for nginx
  ansible.builtin.template:
    src: ../files/elk
    dest: /etc/nginx/sites-enabled/elk
    mode: 0600
  notify: restart nginx
